// Kelompok (small-group) assignment for WIF 2026, 2026-09-26 - one-time,
// event-specific data, NOT a DB table (deliberately - no schema/migration risk
// on the event day itself). Extracted + fuzzy-matched from the committee's own
// "VERIFIKASI WECHAT PESERTA WIF DAN KELOMPOK PESERTA.pdf" against live
// registrant full names. A pure display convenience layered onto check-in -
// if a name here is wrong or missing, check-in itself is UNAFFECTED, the
// kelompok/warna badge just wont show for that one person.
export const WIF_2026_KELOMPOK: Record<string, { kelompok: number; warna: string; koordinator: string }> = {
  "aethan troy sutiana lazaro": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "ahmad vallerie yudakusuma": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "aidan sabian wibisono": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "airine abanna chan": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "akiko kanaya": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "alexander vaio": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "alfiyah rahma": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "alice": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "alika zahratusarah": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "aretha gracella": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "arthur rafael anggraynoh": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "audry mersyela": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "aulya qarina farsya salsabila": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "azam farqulaith": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "azwa anindya putri hendrawan": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "beatrix tandyana": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "berwyn surya": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "beverly kyra": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "callista louise": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "charisma dewi sephira harianto": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "chelsea regina solaiman": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "cheryl athalia": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "chessa angelie junus": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "chloe elizabeth": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "christina cindy": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "chrysabelle chai": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "chrysilla devita": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "clarissa edeline avalokita": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "daniel putra aji sugatha": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "dayton widjaja": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "dehotman yabes hasibuan": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "dharmanadi djainuri": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "edbert jeremy": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "edgina juwy siddharta": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "elbert julius joewono": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "ellysia willim": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "emmanuel tan": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "fauzan zain": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "febrianti": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "felisha rory santanu": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "fidelio stanley sastradi": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "finny violin khosiga": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "flanella jeanell soedarma": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "florencia fransisca": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "florentcia aileen": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "gabriella monica budhisastra": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "garvin paul luo hernando": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "gladys metania tandijo": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "grant savero": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "grizzel alexis marvelyn": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "gwyndolyn": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "hafizd abdurrahman": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "hans philemon limanza": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "hans sebastian": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "ivanna oriana iryanto": { kelompok: 3, warna: "Biru Langit (Muda)", koordinator: "Vincent" },
  "jadynne renea": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "jansen limantoro": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "jayleene valentine herman": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "jennifer jesslynlee": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "jennifer noriss fu": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "jesslyn aurelia": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "jesslynn kayana": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "jherry sangnata citra": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "jonathan shelo": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "juan valentinus setiawan": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "julia ciang": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "justin jiro": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "karyn alineskie": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "katya alexandra lauw": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "kaylaawaaunikhairina": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "kaylin huang": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "kenneth daniel s": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "kenzo chandra": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "khaterine masayu": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "klara suyenti": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "lidwina chrysan": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "mark travis pangemanan": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "marsyalina sugama": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "michelle janice harianto": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "michelle princessia candra": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "miftha rizqani halid masloman": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "muh rezki wahyudi": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "muhammad fauzan": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "muhammad keenan abigail": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "nabilah widiastuti": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "nadhira raisya dhiandraputri": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "najwa zahratul izza": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "natasya aurelia": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "nathael christian sidi": { kelompok: 2, warna: "Hitam", koordinator: "Shem" },
  "nathanael cleon lie": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "nathanael owen lim": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "nathaniel kenzo putra": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "neisya amarilia nurbaiti": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "nicholas alexander gunawan": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "nicholas andrew tanubrata": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "nicole michiko chie": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "patricia faustine suryanto": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "pelangi": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "pia thalia imawan": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "queisha vedana": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "rachel alexa les": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "rachel hangralim": { kelompok: 5, warna: "Pink", koordinator: "Clevera" },
  "rachel novenna": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "reyhan nathannya sasongko": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "reynald aldrich eleazar sinyal": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "reynaldi bagus saputra": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "reynaldo bolang yonardy": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "reynard wijaya": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "richelle joanne handoyo": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "ronato axl alchino": { kelompok: 4, warna: "Dark Green", koordinator: "Wesly" },
  "ruth chiara loudica kustiadi": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "sandra chalisa": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "savero stanley halim": { kelompok: 14, warna: "Ijo Muda", koordinator: "Dustin" },
  "selsi handayani": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "sharon altania": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "shereen aurelia lifie": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "sheryne freya araki": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "siauli ikasaputri": { kelompok: 9, warna: "Putih", koordinator: "Sharon" },
  "silvia": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "stella wijaya": { kelompok: 10, warna: "Ungu", koordinator: "Vennesia" },
  "tanti muliati": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "teresia marampa": { kelompok: 1, warna: "Merah", koordinator: "Geby" },
  "valentino raphael": { kelompok: 12, warna: "Abu-Abu", koordinator: "Gwenny" },
  "valerie angela suryadi": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
  "valerie nathania chai": { kelompok: 8, warna: "Kuning", koordinator: "Rafania" },
  "vanessa areliano wijaya": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "vedrick melvern wijaya": { kelompok: 7, warna: "Orange", koordinator: "Eifellia" },
  "verolin laura": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "vivian lauren viriyadi": { kelompok: 6, warna: "Royal Blue", koordinator: "Merry" },
  "wilhan guslie": { kelompok: 11, warna: "Coklat Kopi", koordinator: "Haikal" },
  "yuriko alwi": { kelompok: 13, warna: "Dark Red", koordinator: "Grace" },
  "zoe miraldo": { kelompok: 15, warna: "Kuning Muda", koordinator: "Stella" },
};

export function normalizeNameForKelompok(fullName: string): string {
  return fullName
    .toLowerCase()
    .replace(/[^a-z\s]/g, " ")
    .split(/\s+/)
    .filter(Boolean)
    .join(" ");
}
